### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by re4lfl0w** [liuyug/django-alipay#9]
```shell
(django1.10) nice123@nice123ui-MBP ~/D/_/d/example> python manage.py migrate                                                                                                master
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/nice123/.virtualenvs/django1.10/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/nice123/.virtualenvs/django1.10/lib/python3.5/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/Users/nice123/.virtualenvs/django1.10/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/nice123/.virtualenvs/django1.10/lib/python3.5/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/nice123/.virtualenvs/django1.10/lib/python3.5/site-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/Users/nice123/.virtualenvs/django1.10/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'alipay.create_direct_pay_by_user.dpn.apps'
```

- python3
- django 1.10.4

**Comment by liuyug** [comment]
请使用 python2。

**Comment by liuyug** [comment]
能否介绍下您当前使用的场景吗？那种方式...

**Comment by re4lfl0w** [comment]
I want to receive the china money in shopping mall. That's all
